In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn import preprocessing
from collections import Counter

In [11]:
df = pd.read_csv("Cleandata.csv")
df

,Unnamed: 0.1,Unnamed: 0,Year,Severity,Start_Lat,Start_Lng,Distance(mi),Street,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Visibility(mi),Wind_Direction,Weather_Condition,Traffic_Signal,Sunrise_Sunset,TimeDiff
0,0,2,2016,2,39.063148,-84.032608,0.010,State Route 32,Williamsburg,Clermont,OH,KI69,36.0,33.3,10.0,SW,Overcast,True,Night,30.0
1,1,3,2016,3,39.747753,-84.205582,0.010,I-75 S,Dayton,Montgomery,OH,KDAY,35.1,31.0,9.0,SW,Mostly Cloudy,False,Night,30.0
2,2,4,2016,2,39.627781,-84.188354,0.010,Miamisburg Centerville Rd,Dayton,Montgomery,OH,KMGY,36.0,33.3,6.0,SW,Mostly Cloudy,True,Day,30.0
3,3,5,2016,3,40.100590,-82.925194,0.010,Westerville Rd,Westerville,Franklin,OH,KCMH,37.9,35.5,7.0,SSW,Light Rain,False,Day,30.0
4,4,6,2016,2,39.758274,-84.230507,0.000,N Woodward Ave,Dayton,Montgomery,OH,KDAY,34.0,31.0,7.0,WSW,Overcast,False,Day,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314280,314280,7652504,2017,2,28.879630,-82.092960,0.722,I-75 S,Wildwood,Sumter,FL,KVVG,80.0,80.0,10.0,VAR,Light Rain with Thunder,False,Day,360.0
314281,314281,7652579,2017,2,37.993881,-92.795869,0.000,Sunny Slope Dr,Camdenton,Camden,MO,KH21,75.0,75.0,10.0,N,Cloudy,False,Day,360.0
314282,314282,7652658,2017,2,46.617235,-113.051251,0.000,US-12 W,Drummond,Granite,MT,K3DU,89.0,89.0,3.0,SSE,Haze,False,Day,360.0
314283,314283,7653119,2017,4,46.672100,-113.153690,9.486,US-12 W,Drummond,Granite,MT,K3DU,57.0,57.0,4.0,CALM,Haze,False,Night,360.0
314284,314284,7653237,2017,3,34.344290,-118.504950,0.430,CA-14 S,Newhall,Los Angeles,CA,K3A6,85.0,85.0,10.0,CALM,Fair,False,Day,360.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314285 entries, 0 to 314284
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0.1       314285 non-null  int64
 1   Unnamed: 0         314285 non-null  int64
 2   Year               314285 non-null  int64
 3   Severity           314285 non-null  int64
 4   Start_Lat          314285 non-null  float64
 5   Start_Lng          314285 non-null  float64
 6   Distance(mi)       314285 non-null  float64
 7   Street             314285 non-null  object
 8   City               314285 non-null  object
 9   County             314285 non-null  object
 10  State              314285 non-null  object
 11  Airport_Code       314285 non-null  object
 12  Temperature(F)     314285 non-null  float64
 13  Wind_Chill(F)      314285 non-null  float64
 14  Visibility(mi)     314285 non-null  float64
 15  Wind_Direction     314285 non-null  object
 16  Weather_Condition  314285 non-null  object
 17  Traffic_Signal     314285 non-null  bool
 18  Sunrise_Sunset     314285 non-null  object
 19  TimeDiff           314285 non-null  float64
dtypes: bool(1), float64(7), int64(4), object(8)
memory usage: 45.9+ MB

In [13]:
df = df.drop(columns=['Unnamed: 0.1','Unnamed: 0'])

In [14]:
df

,Year,Severity,Start_Lat,Start_Lng,Distance(mi),Street,City,County,State,Airport_Code,Temperature(F),Wind_Chill(F),Visibility(mi),Wind_Direction,Weather_Condition,Traffic_Signal,Sunrise_Sunset,TimeDiff
0,2016,2,39.063148,-84.032608,0.010,State Route 32,Williamsburg,Clermont,OH,KI69,36.0,33.3,10.0,SW,Overcast,True,Night,30.0
1,2016,3,39.747753,-84.205582,0.010,I-75 S,Dayton,Montgomery,OH,KDAY,35.1,31.0,9.0,SW,Mostly Cloudy,False,Night,30.0
2,2016,2,39.627781,-84.188354,0.010,Miamisburg Centerville Rd,Dayton,Montgomery,OH,KMGY,36.0,33.3,6.0,SW,Mostly Cloudy,True,Day,30.0
3,2016,3,40.100590,-82.925194,0.010,Westerville Rd,Westerville,Franklin,OH,KCMH,37.9,35.5,7.0,SSW,Light Rain,False,Day,30.0
4,2016,2,39.758274,-84.230507,0.000,N Woodward Ave,Dayton,Montgomery,OH,KDAY,34.0,31.0,7.0,WSW,Overcast,False,Day,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314280,2017,2,28.879630,-82.092960,0.722,I-75 S,Wildwood,Sumter,FL,KVVG,80.0,80.0,10.0,VAR,Light Rain with Thunder,False,Day,360.0
314281,2017,2,37.993881,-92.795869,0.000,Sunny Slope Dr,Camdenton,Camden,MO,KH21,75.0,75.0,10.0,N,Cloudy,False,Day,360.0
314282,2017,2,46.617235,-113.051251,0.000,US-12 W,Drummond,Granite,MT,K3DU,89.0,89.0,3.0,SSE,Haze,False,Day,360.0
314283,2017,4,46.672100,-113.153690,9.486,US-12 W,Drummond,Granite,MT,K3DU,57.0,57.0,4.0,CALM,Haze,False,Night,360.0
314284,2017,3,34.344290,-118.504950,0.430,CA-14 S,Newhall,Los Angeles,CA,K3A6,85.0,85.0,10.0,CALM,Fair,False,Day,360.0

In [15]:
#features = ['Year', 'Severity', 'Start_Lat', 'Start_Lng', 'Distance(mi)', 'Street', 'City', 'County', 'State', 'Airport_Code', 'Temperature(F)', 'Wind_Chill(F)', 'Visibility(mi)', 'Wind_Direction', 'Weather_Condition', 'Traffic_Signal', 'Sunrise_Sunset', 'TimeDiff']
features = ['Year', 'Severity', 'Start_Lat', 'Start_Lng', 'Distance(mi)', 'Temperature(F)', 'Wind_Chill(F)', 'Visibility(mi)', 'TimeDiff']
len(features)

9

In [16]:
def StDev_method (df,n,features):
    """
    Takes a dataframe df of features and returns an index list corresponding to the observations 
    containing more than n outliers according to the standard deviation method.
    """
    outlier_indices = []
    
    for column in features:
        # calculate the mean and standard deviation of the data frame
        data_mean = df[column].mean()
        data_std = df[column].std()
        
        # calculate the cutoff value
        cut_off = data_std * 3
        
        # Determining a list of indices of outliers for feature column        
        outlier_list_column = df[(df[column] < data_mean - cut_off) | (df[column] > data_mean + cut_off)].index
        
        # appending the found outlier indices for column to the list of outlier indices 
        outlier_indices.extend(outlier_list_column)
        
    # selecting observations containing more than x outliers
    outlier_indices = Counter(outlier_indices)        
    multiple_outliers = list( k for k, v in outlier_indices.items() if v > n )
    
    # Calculate the number of records below and above lower and above bound value respectively
    df1 = df[df[column] > data_mean + cut_off]
    df2 = df[df[column] < data_mean - cut_off]
    print('Total number of outliers is:', df1.shape[0]+ df2.shape[0])
    
    return multiple_outliers

In [17]:
# detecting outliers
Outliers_StDev = StDev_method(df,1,features)

# dropping outliers
df_out2 = df.drop(Outliers_StDev, axis = 0).reset_index(drop=True)

Total number of outliers is: 67